// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcyzaeikkdjgtxsfrulg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjeXphZWlra2RqZ3R4c2ZydWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNzY4OTMsImV4cCI6MjA1NTc1Mjg5M30.4jZVyxfQO7zkWkXhdEZhqYP8wWGYcN2yjsF6YvfNvew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);